# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_iot_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devid',
            field=models.CharField(max_length=20),
        ),
    ]
